### ISSUE TITLE
Manage Content for Wordpress site 

### ISSUE THREAD

**Issue by jamiedouglass** [jamiedouglass/ResearchOnKnowing#1]
Setup Research on Knowing website up as wordpress site and manage content and changes from this github repository

**Comment by myklhenn** [comment]
I just learned something really important that I was not previously aware of: 

You can only use GitHub Pages (where a website is contained in a GitHub repository like this one) for "static asset" websites, which is **not** what WordPress is.

So we either will need to host the WordPress sites for Language of Languages and Research on Knowing from a place other than GitHub, or we will need to think of a platform other than WordPress to build the sites on.

If the latter option is eventually chosen, [Jekyll](http://jekyllrb.com/) is a possible alternative website building platform we could use--the one most commonly used for websites on GitHub Pages.

**Comment by jamiedouglass** [comment]
This is important. Glad you discovered it now. We will take a look at [Jekyll](http://jekyllrb.com/) as an alternative to WordPress. Looks interesting. Thanks for finding out about this for us.

**Comment by jamiedouglass** [comment]
I've been reviewing [Jekyll](http://jekyllrb.com/) which looks like a good fit for what me want to do. Therefore, I'm going to close this issue and open a new one to setup Jekyll.
